### ISSUE TITLE
Streamline Release Process and Improve Change Tracking

### ISSUE THREAD

**Issue by bhouston** [drivecore/mycoder#140]
# Streamline Release Process and Improve Change Tracking

## Current State
Currently, we use changesets for versioning and manual publishing with `pnpm -r publish`. This approach has some limitations:
- Submitting changesets is not enforced in the pre-commit hooks
- Manual publishing steps are required
- No integration with GitHub Releases
- No automated changelog generation
- No tagging of releases

## Requirements
1. Make use of GitHub Releases when publishing a new version to NPM
2. Ensure releases are properly tagged in Git
3. Generate a comprehensive changelog for each release
4. Enforce proper recording of changes via either:
   - Enforced changeset creation in pre-commit hooks, or
   - Adoption of conventional commit standard

### Option 1: Enhance Current Changeset Approach
- Add pre-commit hook to enforce changeset creation for relevant changes
- Create automated GitHub Actions workflow for releases that:
  - Bumps versions based on changesets
  - Generates changelog
  - Creates GitHub Release with changelog
  - Tags the release
  - Publishes to NPM

### Option 2: Switch to Conventional Commits
- Implement commitlint to enforce conventional commit format
- Replace changesets with semantic-release or standard-version
- Set up GitHub Actions workflow that:
  - Determines version bump based on commit messages
  - Generates changelog from commit messages
  - Creates GitHub Release with changelog
  - Tags the release
  - Publishes to NPM

## Questions to Consider
- Do we want to maintain backward compatibility with existing changesets?
- Should we implement a release branch strategy (e.g., release branches)?
- Do we need to coordinate releases across packages or can they be versioned independently?

## Next Steps
1. Decide between enhancing changesets or switching to conventional commits
2. Implement the chosen approach
3. Update documentation with new release process
4. Train team members on the new process

**Comment by bhouston** [comment]
# Detailed Release Process Recommendations

## Option 1: Enhanced Changeset Approach

### Benefits
- Minimal changes to existing workflow
- Changeset files provide detailed context for changes
- Team is already familiar with the process
- Supports multi-package repositories with interdependencies

### Implementation Steps

#### 1. Enforce Changeset Creation
Add a pre-commit or pre-push hook to check for changesets:

```javascript
// .husky/pre-push
#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Check if there are uncommitted changes
if git diff-index --quiet HEAD --; then
  # Check if there are any changed files that aren't in .changeset
  CHANGED_FILES=$(git diff --name-only HEAD origin/main)
  PACKAGE_CHANGES=$(echo "$CHANGED_FILES" | grep -E "packages/.*/src/|packages/.*/package.json" || true)
  
  if [ -n "$PACKAGE_CHANGES" ]; then
    RECENT_CHANGESETS=$(git diff --name-only HEAD origin/main | grep -E "\.changeset/.*\.md" || true)
    
    if [ -z "$RECENT_CHANGESETS" ]; then
      echo "❌ Package changes detected but no changesets found!"
      echo "Please run 'pnpm changeset' to document your changes."
      exit 1
    fi
  fi
fi
```

#### 2. Create GitHub Actions Release Workflow

```yaml
# .github/workflows/release.yml
name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.2.1

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm release
          commit: "chore(release): version packages"
          title: "chore(release): version packages"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        if: steps.changesets.outputs.published == 'true'
        run: |
          # Get the version from the most recent tag
          VERSION=$(git describe --tags --abbrev=0)
          
          # Extract changelog for this version
          CHANGELOG=$(node -e "
            const fs = require('fs');
            const path = require('path');
            
            // Function to extract changelog for a specific version
            function getVersionChangelog(pkgName, version) {
              const changelogPath = path.join('packages', pkgName, 'CHANGELOG.md');
              if (!fs.existsSync(changelogPath)) return '';
              
              const content = fs.readFileSync(changelogPath, 'utf8');
              const versionHeader = new RegExp(\`## \${version.replace(/\\./g, '\\\\.')}\`);
              const sections = content.split(/^## /m);
              
              for (const section of sections) {
                if (section.match(new RegExp(\`^\${version.replace(/\\./g, '\\\\.')}\`))) {
                  return section.split(/^## /m)[0].trim();
                }
              }
              return '';
            }
            
            // Get all package directories
            const packagesDir = path.join('packages');
            const packages = fs.readdirSync(packagesDir).filter(dir => 
              fs.statSync(path.join(packagesDir, dir)).isDirectory()
            );
            
            // Build combined changelog
            let changelog = '';
            const version = '$VERSION'.replace('v', '');
            
            for (const pkg of packages) {
              const pkgChangelog = getVersionChangelog(pkg, version);
              if (pkgChangelog) {
                changelog += \`### \${pkg}\n\n\${pkgChangelog}\n\n\`;
              }
            }
            
            console.log(changelog);
          ")
          
          # Create GitHub release
          gh release create "$VERSION" \
            --title "Release $VERSION" \
            --notes "$CHANGELOG" \
            --target main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

#### 3. Update Changeset Configuration
Enable commit integration in `.changeset/config.json`:

```json
{
  "commit": true,
  "fixed": [],
  "linked": [],
  "access": "restricted",
  "baseBranch": "main",
  "updateInternalDependencies": "patch",
  "ignore": []
}
```

#### 4. Create a CHANGELOG.md in the Root
Add a script to generate a root-level CHANGELOG.md that combines all package changelogs:

```javascript
// scripts/generate-root-changelog.js
const fs = require('fs');
const path = require('path');

// Get all package directories
const packagesDir = path.join('packages');
const packages = fs.readdirSync(packagesDir).filter(dir => 
  fs.statSync(path.join(packagesDir, dir)).isDirectory()
);

// Build combined changelog
let rootChangelog = '# Changelog\n\n';

for (const pkg of packages) {
  const changelogPath = path.join('packages', pkg, 'CHANGELOG.md');
  if (fs.existsSync(changelogPath)) {
    const changelog = fs.readFileSync(changelogPath, 'utf8');
    rootChangelog += `## ${pkg}\n\n${changelog}\n\n`;
  }
}

fs.writeFileSync('CHANGELOG.md', rootChangelog);
```

Add this to package.json scripts:
```json
"scripts": {
  "generate-changelog": "node scripts/generate-root-changelog.js",
  "version": "changeset version && pnpm generate-changelog"
}
```

## Option 2: Conventional Commits Approach

### Benefits
- Industry standard approach
- No need for separate changeset files
- Automatic versioning based on commit types
- Better integration with various tools

### Implementation Steps

#### 1. Set Up Commitlint
Install and configure commitlint to enforce conventional commit format:

```bash
pnpm add -D @commitlint/cli @commitlint/config-conventional
```

Create commitlint.config.js:
```javascript
module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'scope-enum': [2, 'always', ['core', 'agent', 'cli', 'deps', 'docs', 'ci', 'chore']],
    'subject-case': [2, 'always', 'sentence-case'],
  }
};
```

Add husky hook:
```bash
# .husky/commit-msg
#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx --no -- commitlint --edit $1
```

#### 2. Install and Configure Semantic Release
Install required packages:

```bash
pnpm add -D semantic-release @semantic-release/changelog @semantic-release/git @semantic-release/github @semantic-release/npm multi-semantic-release
```

Create .releaserc.json in the root:
```json
{
  "branches": ["main"],
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    "@semantic-release/changelog",
    "@semantic-release/npm",
    ["@semantic-release/git", {
      "assets": ["package.json", "CHANGELOG.md"],
      "message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
    }],
    "@semantic-release/github"
  ]
}
```

#### 3. Create GitHub Actions Release Workflow

```yaml
# .github/workflows/release.yml
name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.2.1

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx multi-semantic-release
```

#### 4. Update package.json Files
Update each package's package.json to include:

```json
"publishConfig": {
  "access": "public"
},
"release": {
  "branches": ["main"]
}
```

#### 5. Update Documentation
Create a CONTRIBUTING.md section about commits:

```markdown
## Commit Message Guidelines

We follow the Conventional Commits specification to have a clear commit history that automates our versioning and release process.

### Commit Message Format
Each commit message consists of a **header**, a **body** and a **footer**. The header has a special format that includes a **type**, a **scope** and a **subject**:

```
<type>(<scope>): <subject>
<BLANK LINE>
<body>
<BLANK LINE>
<footer>
```

The **header** is mandatory and the **scope** of the header is optional.

#### Type
Must be one of the following:

* **feat**: A new feature
* **fix**: A bug fix
* **docs**: Documentation only changes
* **style**: Changes that do not affect the meaning of the code (white-space, formatting, etc)
* **refactor**: A code change that neither fixes a bug nor adds a feature
* **perf**: A code change that improves performance
* **test**: Adding missing tests or correcting existing tests
* **chore**: Changes to the build process or auxiliary tools and libraries

#### Scope
The scope should be the name of the package affected (as perceived by the person reading the changelog):

* **core**
* **agent**
* **cli**
* **deps**
* etc.

#### Subject
The subject contains a succinct description of the change:

* use the imperative, present tense: "change" not "changed" nor "changes"
* don't capitalize the first letter
* no dot (.) at the end
```

## Comparison of Approaches

| Feature | Changesets | Conventional Commits |
|---------|------------|----------------------|
| Learning curve | Low (already in use) | Medium (new standard to learn) |
| Documentation | Per-change files | In commit messages |
| Automation | Moderate | High |
| Tooling support | Good | Excellent |
| Multi-package support | Excellent | Good (with multi-semantic-release) |
| GitHub integration | Requires custom scripts | Built-in |
| Industry adoption | Growing | Widespread |

## Recommendation

Based on your requirements and current setup, I recommend **Option 1 (Enhanced Changeset Approach)** for the following reasons:

1. It builds on your existing workflow, minimizing disruption
2. The changeset files provide detailed context that's easier to review
3. It has excellent support for monorepos with interdependent packages
4. The implementation can be done incrementally

However, if you prefer a more standardized approach with broader industry adoption, Option 2 would be the better long-term choice despite the higher initial setup cost.

## Implementation Plan

### Phase 1: Immediate Improvements
1. Add changeset enforcement in pre-push hook
2. Update changeset configuration to enable commit integration
3. Create basic GitHub Release integration

### Phase 2: Full Automation
1. Implement comprehensive GitHub Actions workflow
2. Add root-level changelog generation
3. Update documentation

### Phase 3: Evaluation
1. Evaluate the enhanced changeset approach
2. Consider migration to conventional commits if needed
