### ISSUE TITLE
Fix issue-comment.yml workflow incorrect triggering

### ISSUE THREAD

**Issue by bhouston** [drivecore/mycoder#232]
## GitHub Issue Comment Trigger Investigation

I'm investigating why the issue-comment.yml workflow is being triggered incorrectly. Based on the workflow file, it should only run when:

1. A comment is created on an issue or PR
2. The comment contains the text '/mycoder'
3. The comment is made by the user 'bhouston'

The current workflow definition has:

```yaml
on:
  issue_comment:
    types: [created]

jobs:
  process-comment:
    runs-on: ubuntu-latest
    # Only run if comment contains '/mycoder' AND commenter is in AUTHORIZED_USERS list
    if: |
      contains(github.event.comment.body, '/mycoder') && 
      github.event.comment.user.login == 'bhouston'
```

I need to create a GitHub issue to track this problem and propose a solution.
